<?php

$_lang['moddevtools'] = 'modDevTools';
$_lang['moddevtools_menu_desc'] = 'Assistent für Rapid Development';
$_lang['moddevtools_template_chunks_intro'] = 'Hier können Sie die Chunks, die in diesem Template aufgerufen werden, direkt bearbeiten.';
$_lang['moddevtools_template_snippets_intro'] = 'Hier können Sie die Snippets, die in diesem Template aufgerufen werden, direkt bearbeiten.';
$_lang['moddevtools_chunk_templates_intro'] = 'Hier können Sie die Templates direkt bearbeiten, die einen Aufruf dieses Chunks enthalten.';
$_lang['moddevtools_chunk_chunks_intro'] = 'Hier können Sie die Chunks, die in diesem Chunk aufgerufen werden, direkt bearbeiten.';
$_lang['moddevtools_chunk_snippets_intro'] = 'Hier können Sie die Snippets, die in diesem Chunk aufgerufen werden, direkt bearbeiten.';
$_lang['moddevtools_resource_template_intro'] = 'Diese Tabelle enthält die Ressourcen, die dieses Template zugewiesen haben.';
$_lang['moddevtools_resource_chunk_intro'] = 'Diese Tabelle enthält die Ressourcen, in denen dieser Chunk im Inhalt, im zugewiesenen Template oder verschachtelt in einem Chunk im Inhalt aufgerufen wird.';
$_lang['moddevtools_resource_snippet_intro'] = 'Diese Tabelle enthält die Ressourcen, in denen dieses Snippet im Inhalt, im zugewiesenen Template oder verschachtelt in einem Chunk im Inhalt aufgerufen wird.';
$_lang['moddevtools_grid_actions'] = 'Aktionen';
$_lang['moddevtools_template_change'] = 'Template ändern';
$_lang['moddevtools_search_desc'] = 'Suchen und Ersetzen von Text in Chunks und Templates.';
$_lang['moddevtools_regenerate'] = 'Regenerieren';
$_lang['moddevtools_regenerate_desc'] = 'Regeneriere die Chunk, Template und Snippet Aufruf Links Datenbanktabelle um die zusätzlichen Tabs beim Bearbeiten von Chunks, Templates und Snippets zu befüllen.';
$_lang['moddevtools_regenerate_filters'] = 'Regeneriere die Links auf die folgenden Elemente';
$_lang['moddevtools_regenerate_text'] = 'Regeneriere Links auf [[+type]]: [[+title]] ([[+id]])';
$_lang['moddevtools_text_to_find'] = 'Suchen nach';
$_lang['moddevtools_replace'] = 'Ersetzen';
$_lang['moddevtools_replace_all'] = 'Alle Ersetzen';
$_lang['moddevtools_replace_with'] = 'Ersetzen durch';
$_lang['moddevtools_find'] = 'Suchen';
$_lang['moddevtools_skip'] = 'Überspringen';
$_lang['moddevtools_edit'] = 'Bearbeiten';
$_lang['moddevtools_quickedit'] = 'Schnell bearbeiten';
$_lang['moddevtools_notfound'] = 'Der Suchtext wurde nicht gefunden!';
$_lang['moddevtools_search_filters'] = 'Suche einschränken auf';